	.align 2
gText_ConfirmSave::
	.string "Vols guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ja hi ha un fitxer de guardat.\n"
	.string "Segur que vols sobreescriure'l?$"

gText_SavingDontTurnOff::
	.string "DESANT…\n"
	.string "NO APAGUIS LA CONSOLA.$"

gText_PlayerSavedGame::
	.string "Has guardat la partida.$"

gText_DifferentSaveFile::
	.string "A - TEN - CIÓ!\p"
	.string "Ja hi ha un fitxer de guardat\n"
	.string "diferent.\p"
	.string "Si guardes ara, l'aventura de\n"
	.string "l'altre fitxer, incloent objectes\l"
	.string "i Pokémon, es perdrà completament.\p"
	.string "Segur que vols guardar ara i\n"
	.string "sobreescriure l'altre fitxer?$"

gText_SaveError::
	.string "SAVE ERROR.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "DESANT…\n"
	.string "NO APAGUIS LA CONSOLA.$"
